In [11]:
import pandas as pd
table=['cos','102','is','the','best','course','ever']
data= pd.DataFrame(table)
data

        0
0     cos
1     102
2      is
3     the
4    best
5  course
6    ever

In [14]:
data ={'Name':['Angel','ruby','luis','ade'],
       'Age': [12,15,32,40,],
       'Gender': ['Woman','Male','Male','Woman'],
       'State': ['Lagos','Abia','Lagos','Abuja']
      }

table= pd.DataFrame(data)
table

    Name  Age Gender  State
0  Angel   12  Woman  Lagos
1   ruby   15   Male   Abia
2   luis   32   Male  Lagos
3    ade   40  Woman  Abuja

In [15]:
table[['Name','Age','State']]

    Name  Age  State
0  Angel   12  Lagos
1   ruby   15   Abia
2   luis   32  Lagos
3    ade   40  Abuja

In [16]:
file= pd.read_csv('iris.csv')
file

     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [18]:
row= file.iloc[0]
row

sepal_length            5.1
sepal_width             3.5
petal_length            1.4
petal_width             0.2
class           Iris-setosa
Name: 0, dtype: object

In [21]:
row= file.head(2)
row

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa